<?php /** @var \DVCampus\PersonalDiscount\Block\Product\View\DiscountRequest $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusamus atque, cupiditate dolor, dolores dolorum est et id minima modi necessitatibus nesciunt officia porro recusandae reprehenderit sapiente, sequi velit voluptas?</p>
<div data-bind="scope: 'personalDiscountRequestButton'">
    <!-- ko template: getTemplate() --><!-- /ko -->

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
</div>