<?php /** @var \DVCampus\PersonalDiscount\Block\Product\View\DiscountRequest $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<div data-bind="scope: 'personalDiscountRequestButton'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "personalDiscountRequestButton": {
                        "component": "dvCampusPersonalDiscountButton",
                        "productId": <?= (int) $block->getProduct()->getId() ?>
                    }
                }
            }
        }
    }
</script>