<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusamus atque, cupiditate dolor, dolores dolorum est et id minima modi necessitatibus nesciunt officia porro recusandae reprehenderit sapiente, sequi velit voluptas?</p>
<?php /** @TODO: only logged in customers must be able to make a request. Show login form on button click */ ?>
<button class="action primary" data-mage-init='{"dvCampusPersonalDiscountButton": {}}'>
    <span><?= $escaper->escapeHtml(__('Request Personal Discount')) ?></span>
</button>
