<?php /** @var \DVCampus\PersonalDiscount\Block\Product\View\DiscountRequest $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<div data-bind="scope: 'personalDiscountRequestForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "personalDiscountRequestForm": {
                        "component": "dvCampusPersonalDiscountForm",
                        "action": "<?= $escaper->escapeJs($block->getUrl('dvcampus_personal_discount/index/request')) ?>",
                        "productId": <?= (int) $block->getProduct()->getId() ?>
                    }
                }
            }
        }
    }
</script>
