<?php /** @var \DVCampus\PersonalDiscount\Block\Product\View\DiscountRequestForm $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<div data-bind="scope: 'personalDiscountRequestForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "personalDiscountRequestForm": {
                        "component": "dvCampusPersonalDiscountForm"
                    }
                }
            }
        }
    }
</script>
