<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php /** @TODO: only logged in customers must be able to make a request. Show login form on button click */ ?>
<button class="action primary" data-mage-init='{"dvCampus_personalDiscount_button": {}}'>
    <span><?= $escaper->escapeHtml(__('Request Personal Discount')) ?></span>
</button>
