<?php /** @var \DVCampus\PersonalDiscount\Block\PersonalDiscountInfo $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php if ($personalDiscounts = $block->getPersonalDiscounts()): ?>
    <?php /** @var \DVCampus\PersonalDiscount\Api\Data\DiscountRequestInterface $personalDiscount */
        foreach ($personalDiscounts as $personalDiscount):
    ?>
        <p>
            <span><?= $escaper->escapeHtml($personalDiscount->getMessage()) ?></span>
        </p>
        <p>
            <span><?= $escaper->escapeHtml(__('Request status:')) ?></span>
            <span><?= $escaper->escapeHtml($block->getStatusMessage($personalDiscount)) ?></span>
        </p>
    <?php endforeach; ?>
<?php else: ?>
<p><?= $escaper->escapeHtml(__('No discount request')) ?></p>
<?php endif; ?>
